### ISSUE TITLE
Question #1

### ISSUE THREAD

**Issue by rcon420** [kratos1812/Case-Opening#1]
Hey. Is there even a way to disable Valve skins somehow? force players to have default ones? If possible this could be maybe a future function of your plugin. To have a way to disable valve items from being used on the community server.

Btw I hope we don't piss valve with such ideas : D

**Comment by kratos1812** [comment]
Hmm, that's an interesting ideea: Don'tet players use their real skins, only default ones so that way they will be more interted in the plugin. I will surely add this in the future, thanks foe your contribuition.
