### ISSUE TITLE
just a crazy idea - Drops real

### ISSUE THREAD

**Issue by crashzk** [kratos1812/Case-Opening#2]
I would like to know if it would be possible to implement a real drop system, something like there is in CSGO at the end of the game.

### HOW WOULD IT WORK
API system, something like that, that would have access to a steam profile where it would have the real CSGO skins in the inventory.

At the end of the map, at the end of the game, a player could receive a real drop and the plugin would send it to him, all automatically, an exchange proposal with the drop for whoever won the drop in the game.

This drop system would be fully configurable, leaving a very low percentage to roll a drop, 0.00001 of 100% chance of getting a drop.

It's even possible to show in the game's movie that the players won a DROP as if it were CSGO's.

![drop](https://user-images.githubusercontent.com/32937653/141304558-07be1015-cdb4-448e-aba5-31cb4d788eba.gif)

**Comment by kratos1812** [comment]
Hi, sorry for the late reply.

It's a nice idea but sounds like a lot of work for a small reward. 
Best I could do is provide a native that would like `Action Cases_OnSkinDropped(int iClient, int iSkinId, enum_skin hSkinData, bool bAtMatchEnd);` and more talented devs make your request based on that.

**Comment by crashzk** [comment]
> Hi, sorry for the late reply.
> 
> It's a nice idea but sounds like a lot of work for a small reward. Best I could do is provide a native that would like `Action Cases_OnSkinDropped(int iClient, int iSkinId, enum_skin hSkinData, bool bAtMatchEnd);` and more talented devs make your request based on that.

Thanks, it would be a start.

I'll be seeing if I can find someone willing to make this system in the future, good to know that something like this is possible using your plugin as a base already.
