### ISSUE TITLE
Skins not saving to inventory when quitting and creating a different local match.

### ISSUE THREAD

**Issue by BTFighter** [kratos1812/Case-Opening#3]
Using MariaDB, with a Local Match with bots. When buying skins, quitting and creating another local match, the bought skins in the previous match aren't saved in the inventory in the next match.

**Comment by kratos1812** [comment]
by "local match" you mean listen server(local host)? if so, you should know that sourcemod does not support listen servers

**Comment by BTFighter** [comment]
Not entirely sure what you mean, if you mean "Listen Servers cannot run sourcemod", then that's not the case for me here:
![image](https://user-images.githubusercontent.com/45516471/141688284-b3be9fca-1b65-4006-af4f-d7d66ae4b462.png)

If you mean by something else, then I'm not sure.

**Comment by kratos1812** [comment]
im not saying sourcemod cannot run on listen server, im saying that it is not supported

however, it seems like your issue is related to connecting on the database

**Comment by BTFighter** [comment]
Okay, well thanks for the time anyways.

**Comment by BTFighter** [comment]
I finally realized what causes this issue, if you're using RevEmu, this error causes. I don't know if RevEmu support in this plugin will be implemented but for now don't use RevEmu to play CSGO with this plugin.
