### ISSUE TITLE
Bug on skin market

### ISSUE THREAD

**Issue by jpcrivelini** [kratos1812/Case-Opening#5]
Hi, im testing your plugin and its incredible, but i found 2 bugs and here it is:
1 - When I choose the type of weapon, the values ​​of credits, gloves and skins bug.
2 - When i buy a glove skin, the credits value does not change live, i have to go back one page to update the value and see the real one.

Pictures from bug 1
![Captura de tela 2022-02-17 024424](https://user-images.githubusercontent.com/85125074/154413454-acfb584a-2ca1-4596-ba13-83a53a7681ed.png)
![Captura de tela 2022-02-17 024454](https://user-images.githubusercontent.com/85125074/154413456-e8826f55-e280-4927-8331-6d415f90ec29.png)

**Comment by kratos1812** [comment]
fixed in the latest releas (1.4.0)
